version: 2

checkout:
  post:
    - ./ci-support/checkout_merge_commit.sh
        
aliases:

  - &setup_miniconda
    name: setup_miniconda
    command: |
      mkdir -p workspace
      git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
      ls workspace/cdat
      python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'
      
  - &create_conda_env
    name: create_conda_env
    command: |
       export PATH=$HOME/project/$WORKDIR/miniconda/bin:$PATH
       conda config --set always_yes yes --set changeps1 no
       conda update -y -q conda
       conda config --set anaconda_upload no
       conda list

  - &upload_libdrs
    name: upload_libdrs
    command: |
       export PATH=$HOME/project/$WORKDIR/miniconda/bin:$PATH
       if [ $CIRCLE_BRANCH == "master" ]; then conda install -n root conda-build anaconda-client ; fi
       if [ $CIRCLE_BRANCH == "master" ]; then bash ./ci-support/conda_upload.sh ; fi
       if [ $CIRCLE_BRANCH != "master" ]; then
           export LABEL="unstable";
           conda install -n root conda-build anaconda-client;
           bash ./ci-support/conda_upload.sh;
       fi


jobs:
  macos_libdrs:
    macos:
      xcode: "9.2.0"
    environment:
      WORKDIR: "workspace/test_macos_libdrs"
    steps:
      - checkout
      - run: *setup_miniconda
      - run: *create_conda_env
      - run: *upload_libdrs

  linux_libdrs:
    machine:
      image: circleci/classic:latest
    environment:
      WORKDIR: "workspace/test_linux_libdrs"
    steps:
      - checkout
      - run: *setup_miniconda
      - run: *create_conda_env
      - run: *upload_libdrs
      - store_artifacts:
          path: tests_html
          destination: tests_html
      - store_artifacts:
          path: tests_png
          destination: tests_png

workflows:
  version: 2 
  libdrs:
      jobs:
        - macos_libdrs
#        - linux_libdrs


       
